---
settings:
  parallel: true

driver:
  name: dokken
  use_sudo: false
  privileged: true
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken
  # deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
  - name: centos-7
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN /bin/yum install -y initscripts net-tools wget yum-cron

suites:
  - name: default
    run_list:
      - recipe[kinesis-agent]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
