---
<%
if ENV['JENKINS'] == 'true'
  verifier_format = 'junit'
end
%>
settings:
  parallel: true

driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  always_update_cookbooks: <%= !ENV['CI'] %>

verifier:
  name: inspec
  format: <%= verifier_format || 'cli' %>
  <% if verifier_format == 'junit' %>
  output: test/ci/reports/integration/%{platform}_%{suite}_inspec.xml
  <% end %>

platforms:
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
  # - name: centos-7
  #   driver:
  #     image: centos:7
  #     pid_one_command: /usr/lib/systemd/systemd
  #     provision_command:
  #       - /bin/yum install -y initscripts net-tools wget yum-cron

suites:
  - name: default
    run_list:
      - recipe[kinesis-agent]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
